import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const v_0_1_4_0 = VersionInfo.of({
  version: '0.1.4:0',
  releaseNotes: {
    en_US: `Each rented rig now runs at a share difficulty suited to its own size.\n\nMiningRigRentals scores a rental on the hashrate it measures, and it measures that from accepted shares. A rig left at a difficulty far above its own size produces too few shares to measure well, so a rental that really did deliver can read as underdelivering and a refund claim on it gets declined. Every rental used to be sent the same difficulty whatever its size: measured on the live market, the BLAKE2b rigs listed wanted difficulties from 873 to 20,955, a spread of 24 times across seven rigs, which no single value serves.\n\nThe difficulty comes from the rig's own published optimal range rather than from a calculation on its advertised hashrate, because that range is what the marketplace's own scoring expects, and that scoring is what decides a refund. It travels in the stratum password, which is the only field a rental passes through to the pool untouched. The standard way to ask is sent by the miner itself, and these are third-party rigs whose firmware you do not control, so it is not available here at all.\n\nWhether your endpoint honours the request is detected rather than assumed. The endpoint test now says which it is, and says so plainly when a gateway ignores it, in which case rentals behave exactly as they always did. Datum Gateway (BLAKE2b) Companion 1.0.0.41 honours it.\n\nA rental recovered after an interrupted purchase gets its own difficulty too, and now also recovers the rig name and region that were previously left blank on those rentals.\n\nNothing regresses where the feature does not apply: a rig that publishes no range, an endpoint that ignores the request, and a recovered rental whose rig cannot be looked up all send exactly what they sent before.`,
    es_ES: `Each rented rig now runs at a share difficulty suited to its own size.\n\nMiningRigRentals scores a rental on the hashrate it measures, and it measures that from accepted shares. A rig left at a difficulty far above its own size produces too few shares to measure well, so a rental that really did deliver can read as underdelivering and a refund claim on it gets declined. Every rental used to be sent the same difficulty whatever its size: measured on the live market, the BLAKE2b rigs listed wanted difficulties from 873 to 20,955, a spread of 24 times across seven rigs, which no single value serves.\n\nThe difficulty comes from the rig's own published optimal range rather than from a calculation on its advertised hashrate, because that range is what the marketplace's own scoring expects, and that scoring is what decides a refund. It travels in the stratum password, which is the only field a rental passes through to the pool untouched. The standard way to ask is sent by the miner itself, and these are third-party rigs whose firmware you do not control, so it is not available here at all.\n\nWhether your endpoint honours the request is detected rather than assumed. The endpoint test now says which it is, and says so plainly when a gateway ignores it, in which case rentals behave exactly as they always did. Datum Gateway (BLAKE2b) Companion 1.0.0.41 honours it.\n\nA rental recovered after an interrupted purchase gets its own difficulty too, and now also recovers the rig name and region that were previously left blank on those rentals.\n\nNothing regresses where the feature does not apply: a rig that publishes no range, an endpoint that ignores the request, and a recovered rental whose rig cannot be looked up all send exactly what they sent before.`,
    de_DE: `Each rented rig now runs at a share difficulty suited to its own size.\n\nMiningRigRentals scores a rental on the hashrate it measures, and it measures that from accepted shares. A rig left at a difficulty far above its own size produces too few shares to measure well, so a rental that really did deliver can read as underdelivering and a refund claim on it gets declined. Every rental used to be sent the same difficulty whatever its size: measured on the live market, the BLAKE2b rigs listed wanted difficulties from 873 to 20,955, a spread of 24 times across seven rigs, which no single value serves.\n\nThe difficulty comes from the rig's own published optimal range rather than from a calculation on its advertised hashrate, because that range is what the marketplace's own scoring expects, and that scoring is what decides a refund. It travels in the stratum password, which is the only field a rental passes through to the pool untouched. The standard way to ask is sent by the miner itself, and these are third-party rigs whose firmware you do not control, so it is not available here at all.\n\nWhether your endpoint honours the request is detected rather than assumed. The endpoint test now says which it is, and says so plainly when a gateway ignores it, in which case rentals behave exactly as they always did. Datum Gateway (BLAKE2b) Companion 1.0.0.41 honours it.\n\nA rental recovered after an interrupted purchase gets its own difficulty too, and now also recovers the rig name and region that were previously left blank on those rentals.\n\nNothing regresses where the feature does not apply: a rig that publishes no range, an endpoint that ignores the request, and a recovered rental whose rig cannot be looked up all send exactly what they sent before.`,
    pl_PL: `Each rented rig now runs at a share difficulty suited to its own size.\n\nMiningRigRentals scores a rental on the hashrate it measures, and it measures that from accepted shares. A rig left at a difficulty far above its own size produces too few shares to measure well, so a rental that really did deliver can read as underdelivering and a refund claim on it gets declined. Every rental used to be sent the same difficulty whatever its size: measured on the live market, the BLAKE2b rigs listed wanted difficulties from 873 to 20,955, a spread of 24 times across seven rigs, which no single value serves.\n\nThe difficulty comes from the rig's own published optimal range rather than from a calculation on its advertised hashrate, because that range is what the marketplace's own scoring expects, and that scoring is what decides a refund. It travels in the stratum password, which is the only field a rental passes through to the pool untouched. The standard way to ask is sent by the miner itself, and these are third-party rigs whose firmware you do not control, so it is not available here at all.\n\nWhether your endpoint honours the request is detected rather than assumed. The endpoint test now says which it is, and says so plainly when a gateway ignores it, in which case rentals behave exactly as they always did. Datum Gateway (BLAKE2b) Companion 1.0.0.41 honours it.\n\nA rental recovered after an interrupted purchase gets its own difficulty too, and now also recovers the rig name and region that were previously left blank on those rentals.\n\nNothing regresses where the feature does not apply: a rig that publishes no range, an endpoint that ignores the request, and a recovered rental whose rig cannot be looked up all send exactly what they sent before.`,
    fr_FR: `Each rented rig now runs at a share difficulty suited to its own size.\n\nMiningRigRentals scores a rental on the hashrate it measures, and it measures that from accepted shares. A rig left at a difficulty far above its own size produces too few shares to measure well, so a rental that really did deliver can read as underdelivering and a refund claim on it gets declined. Every rental used to be sent the same difficulty whatever its size: measured on the live market, the BLAKE2b rigs listed wanted difficulties from 873 to 20,955, a spread of 24 times across seven rigs, which no single value serves.\n\nThe difficulty comes from the rig's own published optimal range rather than from a calculation on its advertised hashrate, because that range is what the marketplace's own scoring expects, and that scoring is what decides a refund. It travels in the stratum password, which is the only field a rental passes through to the pool untouched. The standard way to ask is sent by the miner itself, and these are third-party rigs whose firmware you do not control, so it is not available here at all.\n\nWhether your endpoint honours the request is detected rather than assumed. The endpoint test now says which it is, and says so plainly when a gateway ignores it, in which case rentals behave exactly as they always did. Datum Gateway (BLAKE2b) Companion 1.0.0.41 honours it.\n\nA rental recovered after an interrupted purchase gets its own difficulty too, and now also recovers the rig name and region that were previously left blank on those rentals.\n\nNothing regresses where the feature does not apply: a rig that publishes no range, an endpoint that ignores the request, and a recovered rental whose rig cannot be looked up all send exactly what they sent before.`,
  },
  migrations: {
    // Migration 011 is a database migration the app applies itself on start, which is
    // where every schema change for this app lives; StartOS migrations only handle
    // things outside the database. It adds two columns and backfills nothing: existing
    // rentals keep a null password, which every path reads as the 'x' they were created
    // with.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
